apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vd.fullname" . }}-api
  labels:
    {{- include "vd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vd.name" . }}
      component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vd.name" . }}
        component: api
    spec:
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecret }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          env:
{{ toYaml .Values.api.env | indent 12 }}
          ports:
            - containerPort: {{ .Values.api.port }}
