apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vd.fullname" . }}-db-data
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ include "vd.name" . }}
    component: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: microk8s-hostpath

