name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/**'
      - 'deploy/**'

jobs:
  py-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          uv pip install --system -r .devcontainer/requirements.txt

      - name: Run pytest
        run: pytest || (code=$?; [ $code -eq 5 ] && echo "No tests collected; passing" && exit 0 || exit $code)

  py-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          uv pip install --system ruff

      - name: Run ruff
        run: ruff check .

