name: Cleanup Registry

on:
  schedule:
    - cron: '0 3 * * 0'    # every Sunday at 03:00 UTC

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [gui, db, api]
    steps:
      - uses: actions/checkout@v3

      - name: Delete ${{ matrix.package }} Versions
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: ${{ matrix.package }}
          package-type: container
          min-versions-to-keep: 3
          token: ${{ secrets.PAT_TOKEN }}

