name: Build & Push Images

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: IsaiahHarvi # its fine
          password: ${{ secrets.PAT_TOKEN}}

      - name: Build Images
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        run: docker compose build --no-cache

      - name: Push Images
        run: docker compose push
